---
name: Publish Python Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Or use "3.x" to allow for minor version updates

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies with Poetry
        run: poetry install   

      - name: Set PYTHONPATH for tests
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: poetry run pytest  

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        
        run: |
            # Check package metadata
             poetry check -vvv
    
            # Verify package version availability
            poetry run python -c "import requests; print('Package available' if requests.get('https://pypi.org/pypi/deepseek-client-python/json').status_code == 200 else 'Package does not exist')"
          
            poetry publish --build \
              --username __token__ \
              --password "${{ secrets.PYPI_API_TOKEN }}" \
              -vvv