---
name: Publish Python Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Or use "3.x" to allow for minor version updates

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH for tests
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install build tools
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Run tests
        run: pytest

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*